import { Brain, Zap, Target, Link as LinkIcon, Crosshair, Grid3x3 } from 'lucide-react';

export const GAME_CATEGORIES = {
  memory: 'Memory',
  speed: 'Processing Speed',
  attention: 'Attention',
  logic: 'Logic & Reasoning',
  strategy: 'Strategy',
  reaction: 'Reaction',
};

export const games = [
  {
    id: 'number-chain',
    title: 'Number Chain',
    subtitle: 'Mental Math Trainer',
    description: 'Calculate chains of operations in your head. Master sequential processing and working memory.',
    icon: LinkIcon,
    color: 'from-cyan-500 to-purple-500',
    skills: ['Mental Math', 'Working Memory', 'Sequential Processing'],
    path: '/number-chain',
    category: 'memory',
  },
  {
    id: 'speed-truth',
    title: 'Speed Truth',
    subtitle: 'Processing Speed Trainer',
    description: 'Make split-second decisions under time pressure. Different colors demand different speeds.',
    icon: Zap,
    color: 'from-yellow-500 to-red-500',
    skills: ['Processing Speed', 'Decision Making', 'Impulse Control'],
    path: '/speed-truth',
    category: 'speed',
  },
  {
    id: 'focus-flow',
    title: 'Focus Flow',
    subtitle: 'Attention Trainer',
    description: 'Match numbers with color letter counts. Train selective attention and impulse control.',
    icon: Target,
    color: 'from-green-500 to-cyan-500',
    skills: ['Selective Attention', 'Working Memory', 'Impulse Control'],
    path: '/focus-flow',
    category: 'attention',
  },
  {
    id: 'speed-match',
    title: 'Speed Match',
    subtitle: 'Processing Speed Trainer',
    description: 'Make split-second decisions under time pressure. Different shapes should be checked if matched/mismatched.',
    icon: Brain,
    color: 'from-purple-500 to-pink-500',
    skills: ['Working Memory', 'Pattern Recognition', 'Focus'],
    path: '/speed-match',
    category: 'speed',
  },
  {
    id: 'color-match',
    title: 'Color Match',
    subtitle: 'Reaction & Processing Speed',
    description: 'Fast-paced game. Improve hand-eye coordination and reaction time.',
    icon: Crosshair,
    color: 'from-blue-500 to-purple-500',
    skills: ['Reaction Time', 'Pattern Recognition', 'Focus'],
    path: '/color-match',
    category: 'reaction',
  },
  {
    id: 'quick-decision',
    title: 'Quick Decision',
    subtitle: 'Strategy & Planning',
    description: 'Merge tiles strategically. Build planning skills and strategic thinking.',
    icon: Grid3x3,
    color: 'from-orange-500 to-red-500',
    skills: ['Strategic Planning', 'Resource Management', 'Pattern Recognition'],
    path: '/quick-decision',
    category: 'strategy',
  },
  {
    id: 'water-bubble',
    title: 'Water Bubble',
    subtitle: 'Reaction & Math calculation',
    description: 'Quick Math calculation. Improve mental calculation reaction time.',
    icon: Grid3x3,
    color: 'from-blue-500 to-purple-500',
    skills: ['Mental calculation', 'logical thinking'],
    path: '/water-bubble',
    category: 'memory',
  },
  {
    id: 'logic-lattice',
    title: 'Sherlock, learn theory of deduction',
    subtitle: 'Attention & Logical reasoning Trainer',
    description: 'Catch the Culprit. Solve the problem using logical reasoning & attention.',
    icon: Target,
    color: 'from-green-500 to-cyan-500',
    skills: ['Selective Attention', 'Working Memory', 'Logical reasoning'],
    path: '/logic-lattice',
    category: 'logic',
  },
  {
    id: 'glyph-walker',
    title: 'Glyph Walker',
    subtitle: 'Spatial Imagination Trainer',
    description: 'Make split-second decisions under time pressure. Different shapes should be checked if matched/mismatched.',
    icon: Brain,
    color: 'from-purple-500 to-pink-500',
    skills: ['Working Memory', 'Spatial analysis', 'Critcal Thinking', 'Puzzle solve'],
    path: '/glyph-walker',
    category: 'logic',
  },
  {
    id: 'gate-keeper',
    title: 'Gate Keeper',
    subtitle: 'Multi tasking Trainer',
    description: 'Enhance multi tasking capability, force to think process multiple tasks',
    icon: Brain,
    color: 'from-orange-500 to-red-500',
    skills: ['Working Memory', 'Pattern Recognition', 'Focus'],
    path: '/gate-keeper',
    category: 'attention',
  },
  {
    id: 'symbol-seeker',
    title: 'Symbol Seeker',
    subtitle: 'Intiution Building Game',
    description: 'Inductive Reasoning (Pattern Recognition). Each level, the game secretly decides on a "rule". The screen fills with dozens of random, colorful shapes.',
    icon: Grid3x3,
    color: 'from-green-500 to-blue-500',
    skills: ['Strategic Planning', 'Resource Management', 'Pattern Recognition'],
    path: '/symbol-seeker',
    category: 'logic',
  },
  {
    id: 'mind-fold',
    title: 'Mind Fold',
    subtitle: 'Spatial reasoning puzzle',
    description: 'A 3D puzzle game based on those paper-folding IQ tests. You are presented with a 2D "net" and a 3D "target" shape. Your goal is to mentally fold the net to match the target.',
    icon: Brain,
    color: 'from-blue-500 to-purple-500',
    skills: ['Working Memory', 'Imagination', 'Intiution'],
    path: '/mind-fold',
    category: 'logic',
  },
  {
    id: 'neon-defender',
    title: 'Neon Defender',
    subtitle: 'Reaction & Coordination',
    description: 'Fast-paced shooting game. Improve hand-eye coordination and reaction time.',
    icon: Zap,
    color: 'from-purple-500 to-pink-500',
    skills: ['Reaction Time', 'Hand-Eye Coordination', 'Spatial Awareness'],
    path: '/neon-defender',
    category: 'reaction',
  },
  {
    id: 'merge-conquer',
    title: 'Merge & Conquer',
    subtitle: 'Strategy & Planning',
    description: 'Merge tiles strategically. Build planning skills and strategic thinking.',
    icon: Grid3x3,
    color: 'from-orange-500 to-red-500',
    skills: ['Strategic Planning', 'Resource Management', 'Pattern Recognition'],
    path: '/merge-conquer',
    category: 'strategy',
  },
];

export function getGameById(id) {
  return games.find((g) => g.id === id) || null;
}

export function getGamesByCategory(category) {
  return games.filter((g) => g.category === category);
}
